beyond-sw-camp/be12-fin-HOT6-Petlog-FE

- src/pages/mypage/Mypage.vue
> [Feat} 마이페이지 사이드바 구현

- src/App.vue
- src/components/common/Header.vue
- src/pages/home/LandingPage.vue
- src/router/index.js
- src/style.css
- 헤더 로고 클릭 시 홈 이동
- 회원가입/로그인 페이지에서 헤더 안 보이게 설정
- 헤더 컴포넌트, 랜딩 페이지 스타일 수정
> 헤더 로고 클릭 시 홈 이동, 기타 스타일 수정

- src/pages/board/AdvertisementBoard.vue
- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
> [Feat] 자유, 정보 공유, 분양 홍보 게시판 구현

- src/pages/board/AdvertisementBoard.vue
- src/pages/board/BoardRegister.vue
- src/pages/board/BoardSidebar.vue
- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
> [feat] 게시판 수정, 사이드바 구현

- src/pages/mypage/MypageAnswer.vue
- src/pages/mypage/MypageCard.vue
- src/pages/mypage/MypageCardChange.vue
- src/pages/mypage/MypageCardCreate.vue
- src/pages/mypage/MypageCardDetail.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/mypage/MypageComment.vue
- src/pages/mypage/MypagePassword.vue
- src/pages/mypage/MypagePost.vue
- src/pages/mypage/MypageProfile.vue
- src/pages/mypage/MypageQuestion.vue
> [Feat] 마이 페이지들 구현

- src/pages/mypage/MypageProfile.vue
- src/router/index.js
> [feat] 마이페이지 라우터뷰

- src/pages/mypage/Mypage.vue
- src/pages/mypage/MypageAnswer.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/mypage/MypageComment.vue
- src/pages/mypage/MypagePost.vue
- src/pages/mypage/MypageProfile.vue
- src/pages/mypage/MypageQuestion.vue
> [Feat] 마이페이지 CSS 수정

- src/pages/board/AnswerDetail.vue
- src/pages/board/BoardSidebar.vue
- src/pages/board/QnaBoard.vue
> [Feat] Q&A 게시판, 답변글 상세 조회 추가

- src/pages/board/AdvertisementBoard.vue
- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
> [Fix] 게시글 라우터뷰 경로 수정

- src/pages/board/QnaBoard.vue
- src/pages/board/QuestionRegister.vue
- src/router/index.js
> [Feat] Q&A 질문 등록

- src/pages/board/AdvertisementBoard.vue
- src/pages/board/AnswerDetail.vue
- src/pages/board/AnswerRegister.vue
- src/pages/board/BoardRegister.vue
- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/QuestionRegister.vue
> [Style] 스타일 수정

- src/pages/board/PostDetail.vue
> [Feat] 게시글 댓글 수정 기능 구현

- src/pages/board/AnswerDetail.vue
- src/pages/board/AnswerRegister.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/PostRegister.vue
> [Feat] 각 페이지 버튼 알림창 기능 추가

- src/pages/board/PostDetail.vue
- src/pages/board/PostModify.vue
> [Feat] 게시글 수정 페이지 구현, 라우터 뷰 경로 설정

- src/router/index.js
> [Fix] index.js 파일 수정

- src/pages/board/AdvertisementBoard.vue
- src/pages/board/AnswerDetail.vue
- src/pages/board/QuestionModify.vue
- src/router/index.js
> [Feat] 질문 수정 페이지 구현

- src/pages/board/AnswerDetail.vue
- src/pages/board/AnswerModify.vue
- src/pages/board/QuestionModify.vue
- src/pages/board/QuestionRegister.vue
- src/router/index.js
> [Feat] 답변 수정 페이지 구현, 페이지 수정

- src/pages/user/Login.vue
- src/router/index.js
> [Fix] 로그인 페이지, index.js 수정

- src/pages/user/Login.vue
- src/pages/user/Signup.vue
- src/router/index.js
> [Feat] 회원가입 페이지 구현

- src/pages/place/PlaceSidebar.vue
- src/pages/place/SearchBeauty.vue
- src/pages/place/SearchHospital.vue
- src/pages/user/Signup.vue
- src/router/index.js
> [Feat] 주변 미용실, 병원 찾기 페이지 구현

- src/pages/admin/AdminPassword.vue
- src/pages/admin/AdminProfile.vue
- src/pages/admin/BoardCategory.vue
- src/pages/admin/Record.vue
- src/pages/admin/Schedule.vue
- src/pages/mypage/MypageCardChange.vue
- src/pages/mypage/MypageCardDetail.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/user/Notification.vue
> [Feat] 마이페이지 CSS 수정 및 알림 개발

- src/pages/mypage/MypageCardDetail.vue
- src/router/index.js
> [Fix] index.js 수정

- src/pages/common/components/Header.vue
- src/pages/common/components/HeaderDropdown.vue
> [Feat] 헤더 드롭다운 기능 개발

- src/pages/mypage/MypageProfile.vue
- src/pages/mypage/components/MypageDelete.vue
> [Feat] 계정 삭제 기능 추가

- src/pages/place/KakaoMap.vue
- src/pages/place/PlaceSidebar.vue
- src/pages/place/SearchHospital.vue
> [Feat] 지도 기능 개발

- src/pages/admin/Admin.vue
- src/pages/chat/ChatRoom.vue
- src/pages/common/LandingPage.vue
- src/pages/common/components/Header.vue
- src/pages/mypage/Mypage.vue
- src/router/index.js
- src/style.css
> [Fix] router 수정, 스타일 수정

- src/pages/place/KakaoMap.vue
- src/pages/place/SearchBeauty.vue
- src/pages/place/SearchHospital.vue
> [Feat] 지도 전화번호 추가

- src/pages/admin/AdminProfile.vue
- src/pages/mypage/MypageProfile.vue
- src/router/index.js
> [Fix] 이름 수정

- src/pages/board/AnswerRegister.vue
- src/pages/board/PostDetail.vue
- src/pages/board/components/CommentCard.vue
- src/stores/useCommentStore.js
> [Feat] 게시글 댓글 컴포넌트 생성

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/PostDetail.vue
- src/pages/board/components/PostCard.vue
- src/stores/useBoardStore.js
> [Feat] 카테고리 드롭다운으로 검색 기능 구현

- src/pages/mypage/ModifyMypageCard.vue
- src/pages/mypage/Mypage.vue
- src/pages/mypage/MypageCardCreate.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/mypage/MypageProfile.vue
> [Fix] 마이페이지 css 수정

- src/pages/board/QnaBoard.vue
- src/pages/board/components/QuestionCard.vue
- src/stores/useQuestionStore.js
> [Feat] 질문 컴포넌트 생성

- src/pages/board/PostRegister.vue
- src/pages/board/QnaBoard.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/QuestionRegister.vue
- src/router/index.js
- src/stores/useQuestionStore.js
> [Feat] 질문 등록 카드 선택 모달 추가

- src/pages/chat/ChatHeader.vue
- src/pages/chat/ChatRoom.vue
- src/pages/chat/ChatRoomInfo.vue
- src/pages/chat/ChatRoomScheduleCreate2.vue
- src/pages/chat/components/UserCard.vue
- src/stores/useChatStroe.js
대화상대 리스트 의 태그 컴포넌트화 및 피니아 비동기 함수 추가
> [Feat] 채팅방 정보 조회 페이지 컴포넌트

- src/pages/admin/BoardCategory.vue
- src/pages/admin/RecordCategory.vue
- src/pages/admin/ScheduleCategory.vue
- src/pages/admin/components/CategoryItem.vue
- src/stores/useBoardCategoryStore.js
- src/stores/useRecordCategoryStore.js
- src/stores/useScheduleCategoryStore.js
> [Fix] 카테고리 스토어 개발

- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/stores/useAnswerStore.js
- src/stores/useBoardStore.js
> [Feat] 답변 컴포넌트 생성

- src/pages/common/components/Header.vue
> [Fix] 헤더 수정정

- src/pages/schedule/Schedule.vue
- src/pages/schedule/components/Calendar.vue
- src/pages/schedule/components/DetailSchedule.vue
- src/pages/schedule/components/NewScheduleModal.vue
- src/pages/schedule/components/ScheduleCard.vue
- src/stores/useScheduleStore.js
- src/style.css
- src/utils/color.js
- src/utils/dateFormat.js
> [Feat] 새 기록 만들기, 일정 상세 페이지 구현

- src/pages/board/AnswerRegister.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/router/index.js
- src/stores/useAnswerStore.js
- src/stores/useBoardStore.js
> [Feat] Store 연결, 라우터 경로 수정

- src/pages/board/QuestionRegister.vue
> [Fix] 질문 등록 페이지 수정

- src/pages/admin/RecordCategory.vue
> [Fix] 기록 카테고리 CSS 이슈 고침

- src/stores/useBoardCategoryStore.js
- src/stores/useMypageCard.js
- src/stores/useRecordCategoryStore.js
- src/stores/useScheduleCategoryStore.js
> [Fix] 스토어 수정

- src/pages/chat/ChatRoomScheduleCreate2.vue
- src/pages/chat/ChatRoomScheduleDetail.vue
- src/pages/chat/chat-base.css
- src/pages/chat/components/ScheduleCard.vue
- src/stores/useChatStroe.js
현재 내가 이 채팅방의 일정에 참여하고 있는지 아닌지 여부에 따라 화면 다르게!
참여하고 있지 않다면 내 반려동물 정보 가져와서 아래에 추가!
> [Feat] 채팅방의 일정 상세 페이지 컴포넌트 작성

- src/pages/admin/AdminCategory.vue
- src/pages/admin/BoardTypeCategory.vue
- src/pages/admin/RecordCategory.vue
- src/pages/admin/ScheduleCategory.vue
- src/router/index.js
- src/stores/useCategoryStore.js
> [Fix] 카테고리 부분 수정

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/PostDetail.vue
- src/pages/board/PostRegister.vue
- src/pages/board/components/CommentCard.vue
- src/pages/board/components/PostCard.vue
- src/router/index.js
- src/stores/useBoardStore.js
- src/stores/useCommentStore.js
> [Fix] Store 수정, 게시글&댓글 더미데이터 삭제

- .gitignore
- package-lock.json
- package.json
- src/main.js
- src/pages/common/LandingPage.vue
- src/pages/common/components/Header.vue
- src/pages/user/Login.vue
- src/pages/user/Signup.vue
- src/stores/useUserStore.js
- vite.config.js
회원가입 기능 백엔드와 연동
로그인 기능 백엔드와 연동
> [Feat] 회원가입/로그인 기능 백엔드와 연동

- src/pages/board/AnswerRegister.vue
- src/pages/board/PostDetail.vue
- src/pages/board/PostRegister.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/QuestionRegister.vue
- src/pages/board/components/AnswerCard.vue
- src/pages/board/components/CommentCard.vue
- src/pages/board/components/PostCard.vue
- src/pages/board/components/QuestionCard.vue
- src/stores/useAnswerStore.js
- src/stores/useCommentStore.js
- vite.config.js
> [Fix] Store 수정, 변수명 수정

- src/pages/user/Login.vue
- src/pages/user/Signup.vue
- src/stores/useUserStore.js
> [Feat] 카카오 로그인/회원가입 구현

- src/stores/useCommentStore.js
> [Fix] 댓글 axios 경로 수정

- package-lock.json
- src/pages/mypage/MypageCardCreate.vue
- src/pages/mypage/MypageCardDetail.vue
> [Fix] Card 중성화 표시 수정

- src/pages/common/components/Header.vue
- src/stores/useUserStore.js
> [Feat] 카카오 로그아웃 구현

- src/pages/board/AnswerCreate.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/stores/useAnswerStore.js
> [Feat] 답변 수정/삭제 기능 구현

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/PostCreate.vue
- src/pages/board/PostDetail.vue
- src/pages/board/QnaBoard.vue
- src/pages/board/QuestionCreate.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/components/CommentCard.vue
- src/stores/useBoardStore.js
- src/stores/useCommentStore.js
- src/stores/useQuestionStore.js
> [Fix] 게시판 컴포넌트 및 store 수정

- src/pages/user/Login.vue
- src/stores/useUserStore.js
> [Feat] 이메일 인증 구현

- src/pages/mypage/ModifyMypageCard.vue
- src/router/index.js
> [Fix] 반려동물 수정 카드

- src/pages/mypage/ModifyMypageCard.vue
- src/pages/mypage/MypageCardDetail.vue
> [Fix] 반려동물 삭제 수정

- src/main.js
- src/pages/common/HomePage.vue
- src/pages/common/LandingPage.vue
- src/pages/common/components/Header.vue
- src/pages/user/Login.vue
- src/pages/user/Signup.vue
- src/router/index.js
- src/stores/useUserStore.js
- 로그인 여부에 따라 redirect
- oauth2 토큰에 idx 추가
> [Fix] 로그인 여부에 따라 redirect, oauth2 토큰에 idx 추가

- src/pages/board/PostCreate.vue
- src/pages/board/PostDetail.vue
- src/pages/board/QuestionCreate.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/stores/useAnswerStore.js
- src/stores/useBoardStore.js
- src/stores/useCommentStore.js
- src/stores/useQuestionStore.js
- src/stores/useUserStore.js
> [Feat] 게시판 User 연동

- src/pages/board/components/CommentCard.vue
- src/pages/board/components/QuestionCard.vue
> [Feat] 총 답변 수 표시, 게시글 댓글 수정

- src/pages/common/HomePage.vue
- src/pages/mypage/MypageCardDetail.vue
- src/router/index.js
- src/stores/useUserStore.js
> [Fix] 로그인 시 홈페이지 변동

- src/pages/common/LandingPage.vue
- src/pages/user/Login.vue
> [Fix] router 수정

- src/App.vue
- src/pages/common/HomePage.vue
- src/pages/common/components/Header.vue
> [Fix] loading 추가

- src/pages/board/AnswerCreate.vue
- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/PostDetail.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/pages/board/components/CommentCard.vue
- src/pages/board/components/PostCard.vue
- src/pages/board/components/QuestionCard.vue
- src/stores/useCommentStore.js
> [Fix] 게시판 css 수정, 변수명 수정

- src/pages/mypage/ModifyMypageCard.vue
- src/pages/mypage/MypageCardCreate.vue
- src/pages/mypage/MypageCardDetail.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/mypage/MypageProfile.vue
- src/stores/useMypageCard.js
> [Fix] api 요청 수정

- src/pages/mypage/MypageCardCreate.vue
> [Fix] aws S3 사진 업로드

- src/pages/mypage/MypageProfile.vue
> [Fix] 프로필 사진 기능

- src/pages/mypage/MypageCardList.vue
- src/pages/mypage/MypagePost.vue
> [Fix] 사진 기능 & 게시판 유저별 조회

- src/pages/board/components/QuestionCard.vue
- src/pages/mypage/MypageQuestion.vue
> [Fix] 나의 질문 조회

- src/pages/board/components/AnswerCard.vue
- src/pages/mypage/MypageAnswer.vue
> [Fix] 마이페이지 답변 수정

- src/pages/board/AnswerCreate.vue
- src/pages/board/QuestionCreate.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/stores/useAnswerStore.js
- src/stores/useQuestionStore.js
> [Feat] Q&A 게시판 이미지 업로드 기능 구현

- src/pages/board/components/CommentCard.vue
- src/pages/mypage/MypageComment.vue
> [Fix] 댓글 조회 기능

- src/pages/chat/Chat.vue
- src/pages/chat/ChatRoom.vue
- src/pages/chat/components/ChatCard.vue
- src/pages/chat/components/ChatMessages.vue
- src/stores/useChatStroe.js
- src/utils/errorHandler.js
> [Feat] 검색기능 화면 구성( 제목 + 해시태그 )

- src/pages/board/PostCreate.vue
- src/pages/board/PostDetail.vue
- src/pages/board/components/CommentCard.vue
- src/pages/board/components/PostCard.vue
일반 게시글 이미지 업로드 기능 구현, Comment 수정
> [Feat] 일반 게시글 이미지 업로드 기능 구현, Comment 수정

- src/pages/board/AnswerCreate.vue
- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/components/AnswerCard.vue
- src/pages/board/components/QuestionCard.vue
- src/stores/useAnswerStore.js
> [Fix] css수정, 질문 이미지 랜더링 수정

- src/pages/board/PostDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/pages/board/components/CommentCard.vue
- src/pages/board/components/QuestionCard.vue
> [Feat] User 프로필 이미지 게시판 연동

- src/pages/admin/AdminCategory.vue
- src/pages/admin/AdminProfile.vue
- src/pages/admin/BoardCategory.vue
- src/pages/admin/BoardTypeCategory.vue
- src/pages/admin/ModifyBoard.vue
- src/pages/admin/ModifyRecordCategory.vue
- src/pages/admin/ModifyScheduleCategory.vue
- src/pages/admin/RecordCategory.vue
- src/pages/admin/ScheduleCategory.vue
- src/router/index.js
- src/stores/useCategoryStore.js
> [Feat] 카테고리 기능

- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
> [Feat] Ai 답변 기능 구현

- src/pages/mypage/ModifyMypageCard.vue
- src/pages/mypage/MypageCardCreate.vue
- src/pages/mypage/MypageCardDetail.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/mypage/MypageComment.vue
- src/pages/mypage/MypagePost.vue
- src/pages/mypage/MypageProfile.vue
- src/pages/mypage/MypageQuestion.vue
- src/stores/useMypageCard.js
- src/stores/usePetStore.js
> [Fix] usemypagestore 작성

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/PostCreate.vue
> [Fix] 카테고리 기능 강화

- src/pages/common/components/SelectPetModal.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/schedule/Schedule.vue
- src/pages/schedule/components/NewScheduleModal.vue
- src/stores/useCategoryStore.js
- src/stores/usePetStore.js
> [Fix] 일정, 카테고리 기능 강화

- src/pages/mypage/ModifyMypageCard.vue
- src/pages/mypage/MypageCardDetail.vue
- src/stores/usePetStore.js
> [Fix] 유저 펫 연동

- src/pages/mypage/ModifyMypageCard.vue
- src/stores/usePetStore.js
> [Fix] 펫카드 수정 기능

- src/pages/schedule/Schedule.vue
- src/pages/schedule/components/DetailList.vue
- src/pages/schedule/components/NewScheduleModal.vue
- src/pages/schedule/components/ScheduleCard.vue
- src/stores/useScheduleStore.js
- src/utils/dateFormat.js
> [Feat] 기록 생성 기능, 날짜별 기록 조회 기능 구현

- src/pages/admin/Admin.vue
- src/pages/mypage/MypageAnswer.vue
- src/pages/mypage/MypageQuestion.vue
> [Fix]  Feature/mypage

- src/pages/board/AnswerCreate.vue
- src/pages/board/PostCreate.vue
- src/pages/board/PostDetail.vue
- src/pages/board/QnaBoard.vue
- src/pages/board/QuestionCreate.vue
- src/pages/board/QuestionDetail.vue
- src/pages/board/components/AnswerCard.vue
- src/pages/board/components/CommentCard.vue
- src/pages/board/components/QuestionCard.vue
- src/stores/useAnswerStore.js
> [Fix] Q&A 게시판 답변 기능 수정

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/QnaBoard.vue
- src/pages/board/QuestionCreate.vue
- src/stores/useBoardStore.js
- src/stores/useQuestionStore.js
> [Feat] 게시판 페이지네이션 적용

- src/pages/common/components/NoticeDropdown.vue
- src/stores/useNoticeStore.js
> [Feat] 알림기능

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/QnaBoard.vue
- src/stores/useBoardStore.js
- src/stores/useQuestionStore.js
> [Feat] 게시판 검색 결과 페이지네이션 적용

- src/pages/common/components/SelectPetModal.vue
- src/pages/mypage/MypageCardList.vue
- src/pages/schedule/DetailSchedule.vue
- src/pages/schedule/Schedule.vue
- src/pages/schedule/components/Calendar.vue
- src/pages/schedule/components/DetailItem.vue
- src/pages/schedule/components/DetailList.vue
- src/pages/schedule/components/DetailRecordItem.vue
- src/pages/schedule/components/NewScheduleModal.vue
- src/pages/schedule/components/ScheduleCard.vue
- src/stores/useMypageCard.js
- src/stores/usePetStore.js
- src/stores/useScheduleStore.js
- src/utils/dateFormat.js
- 일정/기록 상세 조회 구현
- 반려동물별 일정 조회 구현
- 날짜별 일정/기록 전체 조회 구현
> [Feat] 일정/기록 상세 조회 구현, 반려동물별 일정 조회 구현, 날짜별 일정/기록 전체 조회 구현

- src/pages/common/components/Header.vue
- src/pages/common/components/NoticeDropdown.vue
- src/stores/useMypageCard.js
- src/stores/useNoticeStore.js
> [Feat] 알림 기능

- src/stores/usePetStore.js
> [Fix] url 수정

- src/pages/board/components/CommentCard.vue
- src/stores/useAnswerStore.js
- src/stores/useBoardStore.js
- src/stores/useCommentStore.js
- src/stores/useQuestionStore.js
> [Fix] 백엔드 응답 형식 변경에 맞게 데이터 파싱 수정

- Dockerfile
> [Deploy] 도커파일 추가

- src/pages/board/components/AnswerCard.vue
> [Fix] 채택 버튼 로그인 여부 조건 추가

- src/pages/mypage/MypagePasswordModal.vue
- src/pages/mypage/MypageProfile.vue
- src/stores/useMypageCard.js
> [Fix] 비밀번호 변경 기능

- vite.config.js
> [Fix] vite config 파일 수정

- src/pages/mypage/MypageAnswer.vue
- src/stores/useMypageCard.js
> [Fix] 마이페이지 게시판 데이터 수정

- k8s/frontend-v1-deployment.yml
- k8s/frontend-v1-service.yml
- k8s/frontend-v2-deployment.yml
- k8s/frontend-v2-service.yml
> [Deploy] k8s yml 파일 추가

- src/pages/common/HomePage.vue
- src/stores/useScheduleStore.js
> [Feat] 메인 페이지 오늘의 일정, 참여 채팅방 랜더링

- src/pages/chat/ChatRoomInfo.vue
- src/stores/useChatStroe.js
> [Feat] 채팅방 수정 기능

- src/pages/mypage/ModifyMypageCard.vue
> [Fix] 상태 수정 한글로 바꿈

- src/pages/common/components/NoticeDropdown.vue
- src/stores/useNoticeStore.js
> [Fix] 알림에 반려동물 이름 추가

- k8s/template/frontend-deployment.yml
- k8s/template/frontend-service.yml
> [Fix] service 코드 수정

- k8s/template/frontend-deployment.yml
> [Fix] deployment 수정

- src/pages/user/Signup.vue
> [Feat] 회원가입 입력값 검증 로직 추가

- k8s/template/frontend-deployment.yml
> [Fix] ssl 설정 추가

- src/pages/user/Signup.vue
> [Fix] 회원가입 페이지 수정

- src/pages/board/PostCreate.vue
> [Feat] 게시판 필수 입력 검증 추가

- k8s/template/frontend-deployment.yml
> [Fix] 디플로이먼트 yml파일 수정

- index.html
- k8s/template/frontend-deployment.yml
- src/pages/place/KakaoMap.vue
- src/pages/place/SearchBeauty.vue
- src/pages/place/SearchHospital.vue
- src/pages/user/Login.vue
> [Fix] env 배포

- src/pages/common/components/LoadingSpinner.vue
- src/pages/user/Login.vue
- src/pages/user/Signup.vue
- src/stores/useLoadingStore.js
- src/stores/useUserStore.js
> [Feat] 로딩 상태 추가

- src/pages/admin/AdminProfile.vue
- src/pages/common/components/Header.vue
- src/pages/mypage/MypageProfile.vue
- src/stores/useAdminStore.js
- src/stores/useProfileStore.js
- src/stores/useUserStore.js
> [Feat] 유저 삭제 & 유저 복구

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
> [Fix] 게시판 검색 기능 수정

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
> [Fix] 검색 함수 수정

- src/pages/board/InformationBoard.vue
> [Fix] 게시판 이름 변경

- src/pages/user/Login.vue
> [Fix] 환경변수 수정

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/stores/useBoardStore.js
> [Feat] 더미 데이터 삽입 세팅

- src/pages/user/Login.vue
> [Fix] 회원 탈퇴 에러처리

- src/pages/admin/AdminProfile.vue
- src/stores/useAdminStore.js
> [Fix] 탈퇴 회원 조회

- src/stores/useNoticeStore.js
> [Fix] 오류 수정

- src/stores/useBoardStore.js
> [Fix] 검색 기능 수정

- src/stores/useNoticeStore.js
> [Fix] 웹소켓 오류 해결

- src/pages/board/components/AnswerCard.vue
> [Fix] Q&A 채택 기능 수정

- src/pages/board/QnaBoard.vue
- src/pages/board/components/AnswerCard.vue
- src/stores/useQuestionStore.js
> [Fix] 답변 수 표시 수정

- src/pages/mypage/MypageComment.vue
> [Fix] 댓글 누르면 해당 게시글로 이동

- src/pages/common/components/Header.vue
- src/stores/useNoticeStore.js
> [Fix] 알림 뱃지 수정

- src/pages/admin/AdminEvent.vue
- src/pages/admin/components/AdminEventBox.vue
- src/pages/admin/components/AdminEventModal.vue
> [Fix] 채팅방 인원수 조정 및 시간 외 접속 금지

- src/pages/admin/Admin.vue
- src/pages/admin/AdminEvent.vue
- src/pages/admin/AdminProfile.vue
- src/pages/admin/BoardCategory.vue
- src/pages/admin/BoardTypeCategory.vue
- src/pages/admin/RecordCategory.vue
- src/pages/admin/ScheduleCategory.vue
- src/stores/useAdminStore.js
- src/stores/useChatStore.js
- src/stores/useNoticeStore.js
> [Fix] 전체적인 CSS 수정

- src/pages/board/FreeBoard.vue
- src/pages/board/InformationBoard.vue
- src/pages/board/components/PostCard.vue
- src/pages/board/components/QuestionCard.vue
> [Fix] 게시판 css 수정

- src/pages/common/components/DeleteModal.vue
- src/stores/useScheduleStore.js
> [Fix] 일정 삭제 기능
